# limpio la memoria
rm(list = ls()) # remove all objects
gc() # garbage collection

require("data.table")
require("rpart")
require("rpart.plot")

setwd("/Users/alejandrrodr/Documents/DMUBA/DM-EyF") # establezco la carpeta donde voy a trabajar
# cargo el dataset
dataset <- fread("./datasets/competencia1_2022.csv")

# uso esta semilla para los canaritos
set.seed(102191)

# agrego una variable canarito, random distribucion uniforme en el intervalo [0,1]
dataset[, campo000 := ctrx_quarter / mactivos_margen]
dataset[, campo001 := ctrx_quarter / mcomisiones]
dataset[, campo002 := ctrx_quarter / mprestamos_personales]
dataset[, campo003 := ctrx_quarter / cprestamos_personales]
dataset[, campo004 := ctrx_quarter / mcuentas_saldo]
dataset[, campo005 := ctrx_quarter / mcuenta_corriente]
dataset[, campo006 := ctrx_quarter / ccomisiones_otras]
dataset[, campo007 := ctrx_quarter / mrentabilidad]
dataset[, campo008 := ctrx_quarter / mpasivos_margen]
dataset[, campo009 := ctrx_quarter / mcomisiones_otras]
dataset[, campo010 := ctrx_quarter / cdescubierto_preacordado]
dataset[, campo011 := ctrx_quarter / active_quarter]
dataset[, campo012 := mactivos_margen / ctrx_quarter]
dataset[, campo013 := mactivos_margen / mcomisiones]
dataset[, campo014 := mactivos_margen / mprestamos_personales]
dataset[, campo015 := mactivos_margen / cprestamos_personales]
dataset[, campo016 := mactivos_margen / mcuentas_saldo]
dataset[, campo017 := mactivos_margen / mcuenta_corriente]
dataset[, campo018 := mactivos_margen / ccomisiones_otras]
dataset[, campo019 := mactivos_margen / mrentabilidad]
dataset[, campo020 := mactivos_margen / mpasivos_margen]
dataset[, campo021 := mactivos_margen / mcomisiones_otras]
dataset[, campo022 := mactivos_margen / cdescubierto_preacordado]
dataset[, campo023 := mactivos_margen / active_quarter]
dataset[, campo024 := mprestamos_personales / ctrx_quarter]
dataset[, campo025 := mprestamos_personales / mcomisiones]
dataset[, campo026 := mprestamos_personales / mactivos_margen]
dataset[, campo027 := mprestamos_personales / cprestamos_personales]
dataset[, campo028 := mprestamos_personales / mcuentas_saldo]
dataset[, campo029 := mprestamos_personales / mcuenta_corriente]
dataset[, campo030 := mprestamos_personales / ccomisiones_otras]
dataset[, campo031 := mprestamos_personales / mrentabilidad]
dataset[, campo032 := mprestamos_personales / mpasivos_margen]
dataset[, campo033 := mprestamos_personales / mcomisiones_otras]
dataset[, campo034 := mprestamos_personales / cdescubierto_preacordado]
dataset[, campo035 := mprestamos_personales / active_quarter]
dataset[, campo036 := mcomisiones / ctrx_quarter]
dataset[, campo037 := mcomisiones / mcomisiones]
dataset[, campo038 := mcomisiones / mactivos_margen]
dataset[, campo039 := mcomisiones / cprestamos_personales]
dataset[, campo040 := mcomisiones / mcuentas_saldo]
dataset[, campo041 := mcomisiones / mcuenta_corriente]
dataset[, campo042 := mcomisiones / ccomisiones_otras]
dataset[, campo043 := mcomisiones / mrentabilidad]
dataset[, campo044 := mcomisiones / mpasivos_margen]
dataset[, campo045 := mcomisiones / mcomisiones_otras]
dataset[, campo046 := mcomisiones / cdescubierto_preacordado]
dataset[, campo047 := mcomisiones / active_quarter]
dataset[, campo048 := cprestamos_personales / ctrx_quarter]
dataset[, campo049 := cprestamos_personales / mcomisiones]
dataset[, campo050 := cprestamos_personales / mactivos_margen]
dataset[, campo051 := cprestamos_personales / mprestamos_personales]
dataset[, campo052 := cprestamos_personales / mcuentas_saldo]
dataset[, campo053 := cprestamos_personales / mcuenta_corriente]
dataset[, campo054 := cprestamos_personales / ccomisiones_otras]
dataset[, campo055 := cprestamos_personales / mrentabilidad]
dataset[, campo056 := cprestamos_personales / mpasivos_margen]
dataset[, campo057 := cprestamos_personales / mcomisiones_otras]
dataset[, campo058 := cprestamos_personales / cdescubierto_preacordado]
dataset[, campo059 := cprestamos_personales / active_quarter]
dataset[, campo060 := mcuentas_saldo / ctrx_quarter]
dataset[, campo061 := mcuentas_saldo / mcomisiones]
dataset[, campo062 := mcuentas_saldo / mactivos_margen]
dataset[, campo063 := mcuentas_saldo / mprestamos_personales]
dataset[, campo064 := mcuentas_saldo / cprestamos_personales]
dataset[, campo065 := mcuentas_saldo / mcuenta_corriente]
dataset[, campo066 := mcuentas_saldo / ccomisiones_otras]
dataset[, campo067 := mcuentas_saldo / mrentabilidad]
dataset[, campo068 := mcuentas_saldo / mpasivos_margen]
dataset[, campo069 := mcuentas_saldo / mcomisiones_otras]
dataset[, campo070 := mcuentas_saldo / cdescubierto_preacordado]
dataset[, campo071 := mcuentas_saldo / active_quarter]
dataset[, campo072 := mcuenta_corriente / ctrx_quarter]
dataset[, campo073 := mcuenta_corriente / mcomisiones]
dataset[, campo074 := mcuenta_corriente / mactivos_margen]
dataset[, campo075 := mcuenta_corriente / mprestamos_personales]
dataset[, campo076 := mcuenta_corriente / cprestamos_personales]
dataset[, campo077 := mcuenta_corriente / mcuentas_saldo]
dataset[, campo078 := mcuenta_corriente / ccomisiones_otras]
dataset[, campo079 := mcuenta_corriente / mrentabilidad]
dataset[, campo080 := mcuenta_corriente / mpasivos_margen]
dataset[, campo081 := mcuenta_corriente / mcomisiones_otras]
dataset[, campo082 := mcuenta_corriente / cdescubierto_preacordado]
dataset[, campo083 := mcuenta_corriente / active_quarter]
dataset[, campo084 := ccomisiones_otras / ctrx_quarter]
dataset[, campo085 := ccomisiones_otras / mcomisiones]
dataset[, campo086 := ccomisiones_otras / mactivos_margen]
dataset[, campo087 := ccomisiones_otras / mprestamos_personales]
dataset[, campo088 := ccomisiones_otras / cprestamos_personales]
dataset[, campo089 := ccomisiones_otras / mcuentas_saldo]
dataset[, campo090 := ccomisiones_otras / mcuenta_corriente]
dataset[, campo091 := ccomisiones_otras / mrentabilidad]
dataset[, campo092 := ccomisiones_otras / mpasivos_margen]
dataset[, campo093 := ccomisiones_otras / mcomisiones_otras]
dataset[, campo094 := ccomisiones_otras / cdescubierto_preacordado]
dataset[, campo095 := ccomisiones_otras / active_quarter]
dataset[, campo096 := mrentabilidad / ctrx_quarter]
dataset[, campo097 := mrentabilidad / mcomisiones]
dataset[, campo098 := mrentabilidad / mactivos_margen]
dataset[, campo099 := mrentabilidad / mprestamos_personales]
dataset[, campo100 := mrentabilidad / cprestamos_personales]
dataset[, campo101 := mrentabilidad / mcuentas_saldo]
dataset[, campo102 := mrentabilidad / mcuenta_corriente]
dataset[, campo103 := mrentabilidad / ccomisiones_otras]
dataset[, campo104 := mrentabilidad / mpasivos_margen]
dataset[, campo105 := mrentabilidad / mcomisiones_otras]
dataset[, campo106 := mrentabilidad / cdescubierto_preacordado]
dataset[, campo107 := mrentabilidad / active_quarter]
dataset[, campo108 := mpasivos_margen / ctrx_quarter]
dataset[, campo109 := mpasivos_margen / mcomisiones]
dataset[, campo110 := mpasivos_margen / mactivos_margen]
dataset[, campo111 := mpasivos_margen / mprestamos_personales]
dataset[, campo112 := mpasivos_margen / cprestamos_personales]
dataset[, campo113 := mpasivos_margen / mcuentas_saldo]
dataset[, campo114 := mpasivos_margen / mcuenta_corriente]
dataset[, campo115 := mpasivos_margen / ccomisiones_otras]
dataset[, campo116 := mpasivos_margen / mrentabilidad]
dataset[, campo117 := mpasivos_margen / mcomisiones_otras]
dataset[, campo118 := mpasivos_margen / cdescubierto_preacordado]
dataset[, campo119 := mpasivos_margen / active_quarter]
dataset[, campo120 := mcomisiones_otras / ctrx_quarter]
dataset[, campo121 := mcomisiones_otras / mcomisiones]
dataset[, campo122 := mcomisiones_otras / mactivos_margen]
dataset[, campo123 := mcomisiones_otras / mprestamos_personales]
dataset[, campo124 := mcomisiones_otras / cprestamos_personales]
dataset[, campo125 := mcomisiones_otras / mcuentas_saldo]
dataset[, campo126 := mcomisiones_otras / mcuenta_corriente]
dataset[, campo127 := mcomisiones_otras / ccomisiones_otras]
dataset[, campo128 := mcomisiones_otras / mrentabilidad]
dataset[, campo129 := mcomisiones_otras / mpasivos_margen]
dataset[, campo130 := mcomisiones_otras / cdescubierto_preacordado]
dataset[, campo131 := mcomisiones_otras / active_quarter]
dataset[, campo132 := cdescubierto_preacordado / ctrx_quarter]
dataset[, campo133 := cdescubierto_preacordado / mcomisiones]
dataset[, campo134 := cdescubierto_preacordado / mactivos_margen]
dataset[, campo135 := cdescubierto_preacordado / mprestamos_personales]
dataset[, campo136 := cdescubierto_preacordado / cprestamos_personales]
dataset[, campo137 := cdescubierto_preacordado / mcuentas_saldo]
dataset[, campo138 := cdescubierto_preacordado / mcuenta_corriente]
dataset[, campo139 := cdescubierto_preacordado / ccomisiones_otras]
dataset[, campo140 := cdescubierto_preacordado / mrentabilidad]
dataset[, campo141 := cdescubierto_preacordado / mpasivos_margen]
dataset[, campo142 := cdescubierto_preacordado / mcomisiones_otras]
dataset[, campo143 := cdescubierto_preacordado / active_quarter]
dataset[, campo144 := active_quarter / ctrx_quarter]
dataset[, campo145 := active_quarter / mcomisiones]
dataset[, campo146 := active_quarter / mactivos_margen]
dataset[, campo147 := active_quarter / mprestamos_personales]
dataset[, campo148 := active_quarter / cprestamos_personales]
dataset[, campo149 := active_quarter / mcuentas_saldo]
dataset[, campo150 := active_quarter / mcuenta_corriente]
dataset[, campo151 := active_quarter / ccomisiones_otras]
dataset[, campo152 := active_quarter / mrentabilidad]
dataset[, campo153 := active_quarter / mpasivos_margen]
dataset[, campo154 := active_quarter / cdescubierto_preacordado]
dataset[, campo155 := active_quarter / cdescubierto_preacordado]
dataset[foto_mes == 202101, clase_binaria := ifelse(clase_ternaria == "CONTINUA", "NO", "SI")]

# agrego los siguientes canaritos
for (i in 13:100) dataset[, paste0("canarito", i) := runif(nrow(dataset))]


# Primero  veo como quedan mis arboles
modelo <- rpart(
  formula = "clase_binaria ~ . -clase_ternaria -mcomisiones_mantenimiento -Visa_mpagado",
  data = dataset[foto_mes == 202101, ],
  model = TRUE,
  xval = 0,
  cp = -1,
  minsplit = 2, # dejo que crezca y corte todo lo que quiera
  minbucket = 1,
  maxdepth = 30
)

modelo$variable.importance

# pdf(file = "./work/arbol_canaritos.pdf", width = 28, height = 4)
# prp(modelo, extra = 101, digits = 5, branch = 1, type = 4, varlen = 0, faclen = 0)
# dev.off()
